### ISSUE TITLE
Sign out is not properly placed in Firefox

### ISSUE THREAD

**Issue by lenny-horstink** [crusttech/webapp-unify#19]
In Firefox 65.0.1 (the latest version) the "Sign out" link on the top right is not shown correctly. 

![image](https://user-images.githubusercontent.com/44468809/53482446-7e8df180-3a7f-11e9-8648-3ea2b022e9c5.png)

In Google Chrome it is.

**Comment by zmija** [comment]
Was fixed last week 

![image](https://user-images.githubusercontent.com/8327569/54377713-03832880-4686-11e9-851e-eb7c685421a8.png)
